insert into main.products (sku, price, description, category) values ('SKU0001', 19.99, 'Wireless Mouse with ergonomic design', 'Electronics');
insert into main.products (sku, price, description, category) values ('SKU0002', 499, '4K Ultra HD Smart TV, 55 inches', 'Electronics');
insert into main.products (sku, price, description, category) values ('SKU0003', 29.5, 'Stainless Steel Water Bottle, 1L', 'Home & Kitchen');
insert into main.products (sku, price, description, category) values ('SKU0004', 15, 'Cotton T-Shirt, Unisex, Size M', 'Clothing');
insert into main.products (sku, price, description, category) values ('SKU0005', 120, 'Noise-Cancelling Over-Ear Headphones', 'Electronics');
insert into main.products (sku, price, description, category) values ('SKU0006', 9.99, 'USB-C to USB Adapter', 'Electronics');
insert into main.products (sku, price, description, category) values ('SKU0007', 75, 'Leather Wallet with RFID Protection', 'Accessories');
insert into main.products (sku, price, description, category) values ('SKU0008', 35, 'Yoga Mat with Non-Slip Surface ', 'Sports');
insert into main.products (sku, price, description, category) values ('SKU0009', 220, 'Smartwatch with Heart Rate Monitor', 'Electronics');
insert into main.products (sku, price, description, category) values ('SKU0010', 12.5, 'Ceramic Coffee Mug, 350ml', 'Home & Kitchen');
insert into main.products (sku, price, description, category) values ('SKU0011', 60, 'Bluetooth Portable Speaker', 'Electronics');
insert into main.products (sku, price, description, category) values ('SKU0012', 85, 'Backpack with Laptop Compartment', 'Accessories');
insert into main.products (sku, price, description, category) values ('SKU0013', 18, 'Stainless Steel Cutlery Set, 24 Pieces', 'Home & Kitchen');
insert into main.products (sku, price, description, category) values ('SKU0014', 250, 'Electric Guitar Starter Pack', 'Musical Instr');
insert into main.products (sku, price, description, category) values ('SKU0015', 42, 'Running Shoes, Men''s Size 42', 'Footwear');
insert into main.products (sku, price, description, category) values ('SKU0016', 27.99, 'Digital Bathroom Scale with Body Fat Analyzer', 'Home Appliances');
insert into main.products (sku, price, description, category) values ('SKU0017', 14.99, 'Set of 6 Organic Cotton Socks ', 'Clothing');
insert into main.products (sku, price, description, category) values ('SKU0018', 300, 'DSLR Camera with 18-55mm Lens ', 'Electronics');
insert into main.products (sku, price, description, category) values ('SKU0019', 8.99, 'Hardcover Notebook, A5, 200 Pages', 'Stationery');
insert into main.products (sku, price, description, category) values ('SKU0020', 65, 'Microwave Oven, 20L Capacity', 'Home Appliances');
insert into main.products (sku, price, description, category) values ('SKU0021', 23.5, 'LED Desk Lamp with Adjustable Brightness', 'Home & Kitchen');
insert into main.products (sku, price, description, category) values ('SKU0022', 19, 'Wireless Charger Pad for Smartphones', 'Electronics');
insert into main.products (sku, price, description, category) values ('SKU0023', 55, 'Men''s Quartz Analog Watch with Leather Strap', 'Accessories');
insert into main.products (sku, price, description, category) values ('SKU0024', 30, 'Wooden Chess Set with Folding Board', 'Toys & Games');
insert into main.products (sku, price, description, category) values ('SKU0025', 99, 'Home Security Camera with Night Vision ', 'Electronics');
insert into main.products (sku, price, description, category) values ('SKU0026', 16.5, 'Aromatherapy Essential Oil Diffuser', 'Home & Kitchen');
insert into main.products (sku, price, description, category) values ('SKU0027', 40, 'Professional Blender with 2L Jar', 'Home Appliances');
insert into main.products (sku, price, description, category) values ('SKU0028', 22, 'Kids'' Educational Tablet Toy', 'Toys & Games');
insert into main.products (sku, price, description, category) values ('SKU0029', 110, 'Mechanical Gaming Keyboard with RGB Lighting', 'Electronics');
insert into main.products (sku, price, description, category) values ('SKU0030', 7.5, 'Pack of 10 Ballpoint Pens, Blue Ink', 'Stationery');
